/* 图映 · PDF → 单文件高保真 HTML 引擎（自研、零第三方依赖）
 *
 * 设计目标：
 * 1. PDF 页面在浏览器本地解析，文字、路径与可解码图片重建为固定版式 SVG；
 * 2. 获准嵌入的 TrueType / OpenType 字体以内联 data URL 保存；
 * 3. HTML 只保留固定版式正文，内联样式、页面、图片与字体，不请求外部资源；
 * 4. PDF JavaScript 永不执行，外链注释只允许 http(s) / mailto；
 * 5. 遇到 PDF 专有特性时在工作台给出质量报告，不把查看器菜单写入成品。
 *
 * 契约：window.TYPDFToHTML.convert(bytes, options) → Promise<Result>
 * options: {locale, title, embedFonts, pageLimit, onFirstPage, onProgress, signal}
 */
(function(){
  'use strict';
  var W=typeof window!=='undefined'?window:self, C=W.TYPDFCore;
  if(!C)throw new Error('TYPDFCore 必须先加载');
  var Name=C.Name,Dict=C.Dict,PStream=C.PStream,PStr=C.PStr,isName=C.isName;
  var ID=[1,0,0,1,0,0], MAX_PAGES=800, MAX_DEPTH=18, MAX_ELEMENTS=240000, MAX_IMAGE_PIXELS=48000000;

  function abort(signal){if(signal&&signal.aborted){var e=new DOMException('已取消','AbortError');throw e;}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function attr(v){return esc(v).replace(/\r?\n/g,' ');}
  function fmt(v){v=+v||0;if(Math.abs(v)<1e-8)v=0;return String(Math.round(v*10000)/10000);}
  function matrix(m){return 'matrix('+m.map(fmt).join(' ')+')';}
  function mul(a,b){return [a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]];}
  function point(m,x,y){return [m[0]*x+m[2]*y+m[4],m[1]*x+m[3]*y+m[5]];}
  function cloneMatrix(m){return m.slice(0,6);}
  function resolved(doc,v){return doc.resolve(v);}
  function number(doc,v,d){v=resolved(doc,v);return typeof v==='number'&&isFinite(v)?v:(d||0);}
  function asDict(doc,v){v=resolved(doc,v);return v instanceof Dict?v:null;}
  function asArray(doc,v){v=resolved(doc,v);return Array.isArray(v)?v:null;}
  function nameOf(doc,v){v=resolved(doc,v);return v instanceof Name?v.name:'';}
  function bytesToBase64(bytes){
    var out='',step=0x8000;
    for(var i=0;i<bytes.length;i+=step)out+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(bytes.length,i+step)));
    return btoa(out);
  }
  function latin(bytes){var s='',step=0x8000;for(var i=0;i<bytes.length;i+=step)s+=String.fromCharCode.apply(null,bytes.subarray(i,Math.min(bytes.length,i+step)));return s;}
  function hex(bytes){var s='';for(var i=0;i<bytes.length;i++)s+=(bytes[i]<16?'0':'')+bytes[i].toString(16);return s.toUpperCase();}
  function safeUrl(url){url=String(url||'').trim();return /^(?:https?:|mailto:)/i.test(url)?url:'';}
  function frame(){return new Promise(function(resolve){setTimeout(resolve,0);});}
  function progress(opts,phase,percent,text){if(opts.onProgress)opts.onProgress({phase:phase,percent:percent,text:text||''});}

  /* ---------- 内容流词法 ---------- */
  function Lex(bytes){this.b=bytes;this.p=0;}
  Lex.prototype.ws=function(){var b=this.b;for(;;){while(this.p<b.length&&(/\s/.test(String.fromCharCode(b[this.p]))||b[this.p]===0))this.p++;if(b[this.p]===37){while(this.p<b.length&&b[this.p]!==10&&b[this.p]!==13)this.p++;continue;}break;}};
  Lex.prototype.word=function(){var b=this.b,s=this.p,c;while(this.p<b.length){c=b[this.p];if(c<=32||c===0||c===40||c===41||c===60||c===62||c===91||c===93||c===47||c===37)break;this.p++;}return latin(b.subarray(s,this.p));};
  Lex.prototype.name=function(){var b=this.b,out='';this.p++;while(this.p<b.length){var c=b[this.p];if(c<=32||c===40||c===41||c===60||c===62||c===91||c===93||c===47||c===37)break;this.p++;if(c===35&&this.p+1<b.length){var h=parseInt(latin(b.subarray(this.p,this.p+2)),16);if(!isNaN(h)){out+=String.fromCharCode(h);this.p+=2;continue;}}out+=String.fromCharCode(c);}return C.nm(out);};
  Lex.prototype.literal=function(){var b=this.b,out=[],depth=1;this.p++;while(this.p<b.length){var c=b[this.p++];if(c===92){var e=b[this.p++];if(e===110)out.push(10);else if(e===114)out.push(13);else if(e===116)out.push(9);else if(e===98)out.push(8);else if(e===102)out.push(12);else if(e===10)continue;else if(e===13){if(b[this.p]===10)this.p++;continue;}else if(e>=48&&e<=55){var oct=e-48,k=0;while(k<2&&b[this.p]>=48&&b[this.p]<=55){oct=oct*8+b[this.p++]-48;k++;}out.push(oct&255);}else out.push(e);continue;}if(c===40){depth++;out.push(c);continue;}if(c===41){if(!--depth)break;out.push(c);continue;}out.push(c);}return new PStr(new Uint8Array(out),false);};
  Lex.prototype.hexString=function(){var b=this.b,out=[],hi=-1;this.p++;while(this.p<b.length){var c=b[this.p++],v;if(c===62)break;if(c>=48&&c<=57)v=c-48;else if(c>=65&&c<=70)v=c-55;else if(c>=97&&c<=102)v=c-87;else continue;if(hi<0)hi=v;else{out.push((hi<<4)|v);hi=-1;}}if(hi>=0)out.push(hi<<4);return new PStr(new Uint8Array(out),true);};
  Lex.prototype.array=function(depth){var out=[];this.p++;for(;;){this.ws();if(this.p>=this.b.length)break;if(this.b[this.p]===93){this.p++;break;}out.push(this.next((depth||0)+1));}return out;};
  Lex.prototype.dictionary=function(depth){var level=0,start=this.p;while(this.p<this.b.length){if(this.b[this.p]===60&&this.b[this.p+1]===60){level++;this.p+=2;continue;}if(this.b[this.p]===62&&this.b[this.p+1]===62){this.p+=2;if(!--level)break;continue;}if(this.b[this.p]===40)this.literal();else this.p++;}return {inlineDict:latin(this.b.subarray(start,this.p))};};
  Lex.prototype.next=function(depth){this.ws();if(this.p>=this.b.length)return null;var c=this.b[this.p];if(c===47)return this.name();if(c===40)return this.literal();if(c===60){if(this.b[this.p+1]===60)return this.dictionary(depth);return this.hexString();}if(c===91)return this.array(depth);var w=this.word();if(!w){this.p++;return null;}if(/^[+\-.]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(w))return +w;if(w==='true')return true;if(w==='false')return false;if(w==='null')return null;return {op:w};};
  Lex.prototype.skipInlineImage=function(){var b=this.b;while(this.p<b.length-2){if((b[this.p]===10||b[this.p]===13||b[this.p]===32)&&b[this.p+1]===69&&b[this.p+2]===73&&(b[this.p+3]===undefined||b[this.p+3]<=32)){this.p+=3;return;}this.p++;}};

  /* ---------- PNG 编码 ---------- */
  var CRC_TABLE=null;
  function crc32(bytes){if(!CRC_TABLE){CRC_TABLE=new Uint32Array(256);for(var n=0;n<256;n++){var c=n;for(var k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;CRC_TABLE[n]=c>>>0;}}var crc=0xffffffff;for(var i=0;i<bytes.length;i++)crc=CRC_TABLE[(crc^bytes[i])&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}
  function u32(v){return new Uint8Array([(v>>>24)&255,(v>>>16)&255,(v>>>8)&255,v&255]);}
  function ascii(s){var out=new Uint8Array(s.length);for(var i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return out;}
  function chunk(type,data){var t=ascii(type),body=C.concat([t,data]);return C.concat([u32(data.length),body,u32(crc32(body))]);}
  async function rgbaPNG(width,height,rgba){var rows=new Uint8Array(height*(width*4+1)),row=width*4;for(var y=0;y<height;y++)rows.set(rgba.subarray(y*row,(y+1)*row),y*(row+1)+1);var packed=await C.deflate(rows);if(!packed)throw new Error('当前浏览器缺少 CompressionStream，不能打包 PDF 原始像素');var ihdr=C.concat([u32(width),u32(height),new Uint8Array([8,6,0,0,0])]);return C.concat([new Uint8Array([137,80,78,71,13,10,26,10]),chunk('IHDR',ihdr),chunk('IDAT',packed),chunk('IEND',new Uint8Array(0))]);}
  function sampleRaw(data,index,bpc){if(bpc===8)return data[index]||0;var bit=index*bpc,byte=data[bit>>3]||0,shift=8-bpc-(bit&7),mask=(1<<bpc)-1;return (byte>>shift)&mask;}
  function sampleAt(data,index,bpc){if(bpc===8)return data[index]||0;var bit=index*bpc,byte=data[bit>>3]||0,shift=8-bpc-(bit&7),mask=(1<<bpc)-1;return Math.round(((byte>>shift)&mask)*255/mask);}
  async function lookupBytes(doc,v){v=resolved(doc,v);if(v instanceof PStr)return v.bytes;if(v instanceof PStream)return (await doc.streamBytes(v)).data;return new Uint8Array(0);}
  async function rawRGBA(ctx,stm,data){
    var doc=ctx.doc,d=stm.dict,w=number(doc,d.get('Width')),h=number(doc,d.get('Height')),bpc=number(doc,d.get('BitsPerComponent'),1),space=resolved(doc,d.get('ColorSpace')),kind=nameOf(doc,space),components=0,palette=null,base='';
    if(w<1||h<1||w*h>MAX_IMAGE_PIXELS)throw new Error('图片像素超过安全上限');
    if(Array.isArray(space)&&nameOf(doc,space[0])==='Indexed'){base=nameOf(doc,space[1]);palette=await lookupBytes(doc,space[3]);components=1;kind='Indexed';}
    else if(kind==='DeviceGray'||kind==='G')components=1;
    else if(kind==='DeviceRGB'||kind==='RGB')components=3;
    else if(kind==='DeviceCMYK'||kind==='CMYK')components=4;
    else if(!kind){components=number(doc,d.get('ImageMask'))?1:3;kind=components===1?'DeviceGray':'DeviceRGB';}
    else throw new Error('暂不支持图片色彩空间 '+kind);
    if([1,2,4,8].indexOf(bpc)<0)throw new Error('暂不支持 '+bpc+' bit 图片采样');
    var out=new Uint8Array(w*h*4),decode=asArray(doc,d.get('Decode')),invert=decode&&decode.length>=2&&number(doc,decode[0])>number(doc,decode[1]);
    for(var i=0;i<w*h;i++){
      var r=0,g=0,b=0,a=255;
      if(kind==='Indexed'){
        var ix=sampleRaw(data,i,bpc),baseComp=(base==='DeviceGray'?1:base==='DeviceCMYK'?4:3),at=ix*baseComp;
        if(baseComp===1)r=g=b=palette[at]||0;
        else if(baseComp===3){r=palette[at]||0;g=palette[at+1]||0;b=palette[at+2]||0;}
        else{var cc=(palette[at]||0)/255,mm=(palette[at+1]||0)/255,yy=(palette[at+2]||0)/255,kk=(palette[at+3]||0)/255;r=255*(1-Math.min(1,cc*(1-kk)+kk));g=255*(1-Math.min(1,mm*(1-kk)+kk));b=255*(1-Math.min(1,yy*(1-kk)+kk));}
      }else if(components===1){r=g=b=sampleAt(data,i,bpc);if(invert)r=g=b=255-r;}
      else if(components===3){r=sampleAt(data,i*3,bpc);g=sampleAt(data,i*3+1,bpc);b=sampleAt(data,i*3+2,bpc);}
      else{var c=sampleAt(data,i*4,bpc)/255,m=sampleAt(data,i*4+1,bpc)/255,y=sampleAt(data,i*4+2,bpc)/255,k=sampleAt(data,i*4+3,bpc)/255;r=255*(1-Math.min(1,c*(1-k)+k));g=255*(1-Math.min(1,m*(1-k)+k));b=255*(1-Math.min(1,y*(1-k)+k));}
      var p=i*4;out[p]=r;out[p+1]=g;out[p+2]=b;out[p+3]=a;
    }
    var smask=asDict(doc,d.get('SMask'));
    if(!smask){var resolvedMask=resolved(doc,d.get('SMask'));if(resolvedMask instanceof PStream)smask=resolvedMask;}
    if(smask instanceof PStream){var mg=await doc.streamBytes(smask);if(!mg.filter){var mw=number(doc,smask.dict.get('Width')),mh=number(doc,smask.dict.get('Height')),mb=number(doc,smask.dict.get('BitsPerComponent'),8);if(mw===w&&mh===h)for(i=0;i<w*h;i++)out[i*4+3]=sampleAt(mg.data,i,mb);else ctx.warn('soft-mask-size','图片软蒙版尺寸不同，请对照原文件验收');}else ctx.warn('soft-mask-filter','图片软蒙版编码暂不能合并，请对照原文件验收');}
    return {width:w,height:h,rgba:out};
  }

  /* ---------- 字体 ---------- */
  var WINANSI={128:0x20ac,130:0x201a,131:0x0192,132:0x201e,133:0x2026,134:0x2020,135:0x2021,136:0x02c6,137:0x2030,138:0x0160,139:0x2039,140:0x0152,142:0x017d,145:0x2018,146:0x2019,147:0x201c,148:0x201d,149:0x2022,150:0x2013,151:0x2014,152:0x02dc,153:0x2122,154:0x0161,155:0x203a,156:0x0153,158:0x017e,159:0x0178};
  /* PDF 标准 14 字体通常不携带 Widths；保留 AFM 字宽，避免依赖本机字体测量造成跨设备漂移。 */
  var HELVETICA_WIDTHS=[278,278,355,556,556,889,667,191,333,333,389,584,278,333,278,278,556,556,556,556,556,556,556,556,556,556,278,278,584,584,584,556,1015,667,667,722,722,667,611,778,722,278,500,667,556,833,722,778,667,778,722,667,611,722,667,944,667,667,611,278,278,278,469,556,333,556,556,500,556,556,278,556,556,222,222,500,222,833,556,556,556,556,333,500,278,556,500,722,500,500,500,334,260,334,584];
  var TIMES_WIDTHS=[250,333,408,500,500,833,778,180,333,333,500,564,250,333,250,278,500,500,500,500,500,500,500,500,500,500,278,278,564,564,564,444,921,722,667,667,722,611,556,722,722,333,389,722,611,889,722,722,556,722,667,556,611,722,722,944,722,722,611,333,278,333,469,500,333,444,500,444,500,444,333,500,500,278,278,500,278,778,500,500,500,500,333,389,278,500,500,722,500,500,444,480,200,480,541];
  function standardWidth(base,code){if(code<32||code>126)return 0;var name=String(base||'').replace(/^\/?[A-Z]{6}\+/,'');if(/Courier/i.test(name))return 600;if(/Helvetica|Arial/i.test(name))return HELVETICA_WIDTHS[code-32]||0;if(/Times/i.test(name))return TIMES_WIDTHS[code-32]||0;return 0;}
  function utf16(hexText){var out='';for(var i=0;i+3<hexText.length;i+=4){var code=parseInt(hexText.slice(i,i+4),16);if(code>=0xd800&&code<=0xdbff&&i+7<hexText.length){var low=parseInt(hexText.slice(i+4,i+8),16);if(low>=0xdc00&&low<=0xdfff){out+=String.fromCodePoint(0x10000+(code-0xd800)*1024+low-0xdc00);i+=4;continue;}}out+=String.fromCharCode(code);}return out;}
  function cmap(bytes){var text=latin(bytes),map=new Map(),max=1,m;
    var sections=/beginbfchar([\s\S]*?)endbfchar/g,block=/<\s*([0-9A-Fa-f]+)\s*>\s*<\s*([0-9A-Fa-f]+)\s*>/g,part;
    while((part=sections.exec(text)))while((m=block.exec(part[1]))){var key=m[1].toUpperCase();if(key.length%2)continue;map.set(key,utf16(m[2]));max=Math.max(max,key.length/2);}
    sections=/beginbfrange([\s\S]*?)endbfrange/g;
    var range=/<\s*([0-9A-Fa-f]+)\s*>\s*<\s*([0-9A-Fa-f]+)\s*>\s*(?:<\s*([0-9A-Fa-f]+)\s*>|\[([^\]]+)\])/g;
    while((part=sections.exec(text)))while((m=range.exec(part[1]))){var from=parseInt(m[1],16),to=parseInt(m[2],16),width=m[1].length;if(to-from>4096)continue;if(m[3]){var base=parseInt(m[3],16),dstWidth=m[3].length;for(var n=from;n<=to;n++){var k=n.toString(16).toUpperCase().padStart(width,'0'),v=(base+n-from).toString(16).toUpperCase().padStart(dstWidth,'0');map.set(k,utf16(v));}}else{var values=m[4].match(/<\s*([0-9A-Fa-f]+)\s*>/g)||[];for(n=from;n<=to&&n-from<values.length;n++){var hx=values[n-from].replace(/[^0-9A-Fa-f]/g,'');map.set(n.toString(16).toUpperCase().padStart(width,'0'),utf16(hx));}}max=Math.max(max,width/2);}
    return {map:map,max:max};
  }
  function sfntPolicy(bytes){if(bytes.length<12)return {browser:false,embed:false,reason:'不是浏览器可用的 OpenType 字体'};var sig=latin(bytes.subarray(0,4)),browser=sig==='OTTO'||sig==='true'||(bytes[0]===0&&bytes[1]===1&&bytes[2]===0&&bytes[3]===0);if(!browser)return {browser:false,embed:false,reason:'Type 1 / CFF 裸字体需要轮廓兜底'};var view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),count=view.getUint16(4),fsType=0;for(var i=0;i<count&&12+i*16+16<=bytes.length;i++){var at=12+i*16;if(latin(bytes.subarray(at,at+4))==='OS/2'){var off=view.getUint32(at+8);if(off+10<=bytes.length)fsType=view.getUint16(off+8);break;}}if(fsType&0x0002)return {browser:true,embed:false,fsType:fsType,reason:'字体许可禁止嵌入'};if(fsType&0x0200)return {browser:true,embed:false,fsType:fsType,reason:'字体许可只允许位图嵌入'};return {browser:true,embed:true,fsType:fsType,previewOnly:!!(fsType&4),noSubset:!!(fsType&0x0100),reason:(fsType&4)?'仅预览/打印嵌入':''};}
  function baseFamily(name){name=String(name||'').replace(/^\/?[A-Z]{6}\+/,'').replace(/[,_-]+/g,' ');if(/courier/i.test(name))return 'Courier New,monospace';if(/times|serif/i.test(name))return 'Times New Roman,serif';if(/symbol/i.test(name))return 'serif';return 'Arial,sans-serif';}
  async function fontInfo(ctx,key,resources){
    var fonts=asDict(ctx.doc,resources&&resources.get('Font')),font=fonts&&asDict(ctx.doc,fonts.get(key));if(!font)return null;
    if(ctx.fontCache.has(font))return ctx.fontCache.get(font);
    var doc=ctx.doc,subtype=nameOf(doc,font.get('Subtype')),base=nameOf(doc,font.get('BaseFont'))||key,descendant=subtype==='Type0'?(asArray(doc,font.get('DescendantFonts'))||[])[0]:font,desc=asDict(doc,asDict(doc,descendant)&&asDict(doc,descendant).get('FontDescriptor'))||asDict(doc,font.get('FontDescriptor')),info={font:font,key:key,subtype:subtype,base:base,family:baseFamily(base),map:new Map(),codeSize:subtype==='Type0'?2:1,widths:new Map(),defaultWidth:1000,embedded:false,restricted:false,hasToUnicode:false,mappingFallback:false,unavailable:false};
    ctx.fontCache.set(font,info);
    var tu=resolved(doc,font.get('ToUnicode'));if(tu instanceof PStream){try{var cg=await doc.streamBytes(tu),cm=cmap(cg.data);info.map=cm.map;info.codeSize=Math.max(info.codeSize,cm.max);info.hasToUnicode=cm.map.size>0;}catch(_e){ctx.warn('font-cmap','字体 '+base+' 的 ToUnicode 映射无法读取');}}
    var encoding=resolved(doc,font.get('Encoding')),encodingName=encoding instanceof Name?encoding.name:'';if(!info.hasToUnicode&&(subtype==='Type0'||encoding instanceof Dict||(encodingName&&encodingName!=='WinAnsiEncoding'&&encodingName!=='StandardEncoding')))info.mappingFallback=true;
    if(subtype==='Type3'){var differences=encoding instanceof Dict?(asArray(doc,encoding.get('Differences'))||[]):[],glyphs=new Map(),code=-1;for(var d=0;d<differences.length;d++){var entry=resolved(doc,differences[d]);if(typeof entry==='number')code=entry;else if(entry instanceof Name&&code>=0)glyphs.set(code++,entry.name);}info.type3={charProcs:asDict(doc,font.get('CharProcs'))||new Dict(),resources:asDict(doc,font.get('Resources'))||resources,matrix:(asArray(doc,font.get('FontMatrix'))||[.001,0,0,.001,0,0]).map(Number),glyphs:glyphs,symbols:new Map()};}
    if(subtype==='Type0'){
      descendant=asDict(doc,descendant);if(descendant){info.defaultWidth=number(doc,descendant.get('DW'),1000);var widths=asArray(doc,descendant.get('W'))||[],i=0;while(i<widths.length){var first=number(doc,widths[i++]),next=resolved(doc,widths[i++]);if(Array.isArray(next)){for(var j=0;j<next.length;j++)info.widths.set(first+j,number(doc,next[j],info.defaultWidth));}else{var last=number(doc,next),value=number(doc,widths[i++],info.defaultWidth);for(j=first;j<=last&&j-first<65536;j++)info.widths.set(j,value);}}}
    }else{var firstChar=number(doc,font.get('FirstChar')),arr=asArray(doc,font.get('Widths'))||[];for(var q=0;q<arr.length;q++)info.widths.set(firstChar+q,number(doc,arr[q],1000));if(desc)info.defaultWidth=number(doc,desc.get('MissingWidth'),1000);}
    var file=desc&&(resolved(doc,desc.get('FontFile2'))||resolved(doc,desc.get('FontFile3'))||resolved(doc,desc.get('FontFile')));if(ctx.options.embedFonts!==false&&file instanceof PStream){try{var fb=await doc.streamBytes(file);if(fb.filter)throw new Error('字体流使用了不支持的过滤器');var policy=sfntPolicy(fb.data),alreadySubset=/^[A-Z]{6}\+/.test(base);if(policy.noSubset&&alreadySubset)policy={browser:policy.browser,embed:false,fsType:policy.fsType,reason:'字体许可要求完整嵌入，但 PDF 只含子集'};if(policy.embed){var family='ImgIngPDF_'+ctx.fontFaces.length,signature=latin(fb.data.subarray(0,4)),mime=signature==='OTTO'?'font/otf':'font/ttf',format=signature==='OTTO'?'opentype':'truetype';info.family=family;info.embedded=true;ctx.fontFaces.push('@font-face{font-family:"'+family+'";src:url(data:'+mime+';base64,'+bytesToBase64(fb.data)+') format("'+format+'");font-display:block}');ctx.report.fontsEmbedded++;if(policy.previewOnly)ctx.warn('font-preview-only','字体 '+base+' 仅获准用于预览/打印，导出页保持只读');}else{info.restricted=true;ctx.report.fontsRestricted++;ctx.warn('font-restricted',base+'：'+policy.reason);}}catch(e){ctx.warn('font-read',base+'：'+e.message);}}
    if(subtype!=='Type3'&&!info.embedded&&!/^(?:[A-Z]{6}\+)?(?:Courier|Helvetica|Times|Symbol|ZapfDingbats)(?:-|$)/i.test(base))info.unavailable=true;
    return info;
  }
  function decodeText(info,bytes){var text='',codes=[],i=0;while(i<bytes.length){var size=Math.min(info?info.codeSize:1,bytes.length-i),key='',found='';for(var trySize=size;trySize>=1;trySize--){key=hex(bytes.subarray(i,i+trySize));if(info&&info.map.has(key)){found=info.map.get(key);size=trySize;break;}}var code=0;for(var j=0;j<size;j++)code=code*256+bytes[i+j];if(!found){var cp=code;if(size===1&&WINANSI[code])cp=WINANSI[code];found=cp<=0x10ffff?String.fromCodePoint(cp):'�';}text+=found;codes.push({code:code,text:found});i+=size;}return {text:text,codes:codes};}

  /* ---------- 页面绘制 ---------- */
  function colorGray(v){var n=Math.max(0,Math.min(255,Math.round((+v||0)*255))),h=n.toString(16).padStart(2,'0');return '#'+h+h+h;}
  function colorRGB(a){return 'rgb('+[0,1,2].map(function(i){return Math.max(0,Math.min(255,Math.round((+a[i]||0)*255)));}).join(',')+')';}
  function colorCMYK(a){var c=+a[0]||0,m=+a[1]||0,y=+a[2]||0,k=+a[3]||0;return 'rgb('+[c,m,y].map(function(v){return Math.round(255*(1-Math.min(1,v*(1-k)+k)));}).join(',')+')';}
  function colorForSpace(space,a){if(space==='DeviceGray'||space==='G')return colorGray(a[0]);if(space==='DeviceCMYK'||space==='CMYK')return colorCMYK(a);return colorRGB(a);}
  function pdfFunction(doc,fn,x){
    fn=asDict(doc,fn);if(!fn)return [x];var type=number(doc,fn.get('FunctionType'));
    if(type===2){var c0=asArray(doc,fn.get('C0'))||[0],c1=asArray(doc,fn.get('C1'))||[1],n=number(doc,fn.get('N'),1),p=Math.pow(Math.max(0,Math.min(1,x)),n),out=[];for(var i=0;i<Math.max(c0.length,c1.length);i++)out.push(number(doc,c0[i],0)+p*(number(doc,c1[i],1)-number(doc,c0[i],0)));return out;}
    if(type===3){var domain=asArray(doc,fn.get('Domain'))||[0,1],functions=asArray(doc,fn.get('Functions'))||[],bounds=asArray(doc,fn.get('Bounds'))||[],encode=asArray(doc,fn.get('Encode'))||[],lo=number(doc,domain[0]),hi=number(doc,domain[1],1),v=Math.max(lo,Math.min(hi,x)),part=0;while(part<bounds.length&&v>=number(doc,bounds[part]))part++;var left=part?number(doc,bounds[part-1]):lo,right=part<bounds.length?number(doc,bounds[part]):hi,e0=number(doc,encode[part*2]),e1=number(doc,encode[part*2+1],1),mapped=right===left?e0:e0+(v-left)/(right-left)*(e1-e0);return pdfFunction(doc,functions[part],mapped);}
    return [x];
  }
  function gs(){return {ctm:ID.slice(),fill:'#000',stroke:'#000',fillSpace:'DeviceGray',strokeSpace:'DeviceGray',fillAlpha:1,strokeAlpha:1,lineWidth:1,lineCap:0,lineJoin:0,miter:10,dash:[],dashPhase:0,blend:'normal',clips:[],fontKey:'',fontSize:12,charSpace:0,wordSpace:0,hScale:1,leading:0,rise:0,renderMode:0,textMatrix:ID.slice(),lineMatrix:ID.slice(),inText:false};}
  function cloneGS(s){var n=Object.assign({},s);n.ctm=cloneMatrix(s.ctm);n.clips=s.clips.slice();n.dash=s.dash.slice();n.textMatrix=cloneMatrix(s.textMatrix);n.lineMatrix=cloneMatrix(s.lineMatrix);return n;}
  function blend(name){var map={Multiply:'multiply',Screen:'screen',Overlay:'overlay',Darken:'darken',Lighten:'lighten',ColorDodge:'color-dodge',ColorBurn:'color-burn',HardLight:'hard-light',SoftLight:'soft-light',Difference:'difference',Exclusion:'exclusion',Hue:'hue',Saturation:'saturation',Color:'color',Luminosity:'luminosity'};return map[name]||'normal';}
  function pageMatrix(box,rotation,user){var x0=box[0]*user,y0=box[1]*user,x1=box[2]*user,y1=box[3]*user,w=x1-x0,h=y1-y0,r=((rotation%360)+360)%360;if(r===90)return {width:h,height:w,m:[0,user,user,0,-box[1]*user,-box[0]*user]};if(r===180)return {width:w,height:h,m:[-user,0,0,user,box[2]*user,-box[1]*user]};if(r===270)return {width:h,height:w,m:[0,-user,-user,0,box[3]*user,box[2]*user]};return {width:w,height:h,m:[user,0,0,-user,-box[0]*user,box[3]*user]};}
  function addElement(ctx,page,markup,clips){if(ctx.report.elements>=MAX_ELEMENTS)throw new Error('页面元素超过安全上限');for(var i=(clips||[]).length-1;i>=0;i--)markup='<g clip-path="url(#'+clips[i]+')">'+markup+'</g>';page.elements.push(markup);ctx.report.elements++;}
  function pathStyle(s,fill,stroke,even){var out='';if(fill)out+=' fill="'+attr(s.fill)+'" fill-opacity="'+fmt(s.fillAlpha)+'" fill-rule="'+(even?'evenodd':'nonzero')+'"';else out+=' fill="none"';if(stroke)out+=' stroke="'+attr(s.stroke)+'" stroke-opacity="'+fmt(s.strokeAlpha)+'" stroke-width="'+fmt(s.lineWidth)+'" stroke-linecap="'+['butt','round','square'][s.lineCap||0]+'" stroke-linejoin="'+['miter','round','bevel'][s.lineJoin||0]+'" stroke-miterlimit="'+fmt(s.miter)+'"'+(s.dash.length?' stroke-dasharray="'+s.dash.map(fmt).join(' ')+'" stroke-dashoffset="'+fmt(s.dashPhase)+'"':'');if(s.blend!=='normal')out+=' style="mix-blend-mode:'+s.blend+'"';return out;}
  function pathPoint(path,s,x,y,command){var p=point(s.ctm,+x||0,+y||0);path.d.push(command+fmt(p[0])+' '+fmt(p[1]));return p;}
  function pageWarn(page,code){if(page.flags.indexOf(code)<0)page.flags.push(code);}
  function patternResource(ctx,name,resources){var patterns=asDict(ctx.doc,resources&&resources.get('Pattern'));return patterns?resolved(ctx.doc,patterns.get(name)):null;}
  function patternKey(page,state,color){return page.index+'|'+state.ctm.map(fmt).join(',')+'|'+color;}
  async function patternPaint(ctx,page,name,resources,state,depth,seen,color){
    var source=patternResource(ctx,name,resources),dict=source instanceof PStream?source.dict:asDict(ctx.doc,source);if(!dict)return '';
    var cache=ctx.patternCache.get(source);if(!cache){cache=new Map();ctx.patternCache.set(source,cache);}var key=patternKey(page,state,color),cached=cache.get(key);if(cached)return cached;
    var id='p'+page.index+'pat'+page.defs.length,type=number(ctx.doc,dict.get('PatternType')),pm=asArray(ctx.doc,dict.get('Matrix'))||ID,combined=mul(page.outputMatrix||ID,pm.map(Number));cache.set(key,id);
    if(type===2){var shading=asDict(ctx.doc,dict.get('Shading')),shadeType=number(ctx.doc,shading&&shading.get('ShadingType')),coords=asArray(ctx.doc,shading&&shading.get('Coords'))||[],space=nameOf(ctx.doc,shading&&shading.get('ColorSpace'))||'DeviceRGB';if(shadeType!==2||coords.length<4){cache.delete(key);return '';}var a=point(combined,+coords[0],+coords[1]),b=point(combined,+coords[2],+coords[3]),fn=shading.get('Function'),stops=[];for(var i=0;i<=16;i++){var at=i/16,components=pdfFunction(ctx.doc,fn,at);stops.push('<stop offset="'+fmt(at*100)+'%" stop-color="'+attr(colorForSpace(space,components))+'"/>');}page.defs.push('<linearGradient id="'+id+'" gradientUnits="userSpaceOnUse" x1="'+fmt(a[0])+'" y1="'+fmt(a[1])+'" x2="'+fmt(b[0])+'" y2="'+fmt(b[1])+'">'+stops.join('')+'</linearGradient>');ctx.report.patterns++;return id;}
    if(type===1&&source instanceof PStream){var got=await ctx.doc.streamBytes(source);if(got.filter){pageWarn(page,'pattern');ctx.warn('pattern','图案内容流无法解码，请对照原文件验收');cache.delete(key);return '';}var bbox=asArray(ctx.doc,dict.get('BBox'))||[0,0,1,1],xstep=Math.abs(number(ctx.doc,dict.get('XStep'),bbox[2]-bbox[0]))||1,ystep=Math.abs(number(ctx.doc,dict.get('YStep'),bbox[3]-bbox[1]))||1,local={index:page.index+'p'+page.defs.length,elements:[],defs:[],flags:page.flags},pstate=gs();pstate.fill=color;pstate.stroke=color;await renderContent(ctx,local,got.data,asDict(ctx.doc,dict.get('Resources'))||resources,pstate,depth+1,seen.concat([source]));for(i=0;i<local.defs.length;i++)page.defs.push(local.defs[i]);page.defs.push('<pattern id="'+id+'" patternUnits="userSpaceOnUse" x="'+fmt(bbox[0])+'" y="'+fmt(bbox[1])+'" width="'+fmt(xstep)+'" height="'+fmt(ystep)+'" patternTransform="'+matrix(combined)+'"><g>'+local.elements.join('')+'</g></pattern>');ctx.report.patterns++;return id;}
    cache.delete(key);return '';
  }
  async function type3Symbol(ctx,page,info,code,depth,seen){
    var type3=info&&info.type3,glyph=type3&&type3.glyphs.get(code);if(!glyph)return '';var source=resolved(ctx.doc,type3.charProcs.get(glyph));if(!(source instanceof PStream))return '';
    var key=glyph,known=type3.symbols.get(key);if(known)return known;var got=await ctx.doc.streamBytes(source);if(got.filter){pageWarn(page,'type3');ctx.warn('type3','Type 3 字形 '+glyph+' 的内容流无法解码');return '';}
    var local={index:'s'+ctx.sharedDefs.length,elements:[],defs:[],flags:page.flags},state=gs();state.ctm=type3.matrix.slice();state.fill='currentColor';state.stroke='currentColor';await renderContent(ctx,local,got.data,type3.resources,state,depth+1,seen.concat([source]));var markup=local.elements.join(''),shared=!local.defs.length&&ctx.type3MarkupCache.get(markup),id;if(shared){type3.symbols.set(key,shared);return shared;}id='t3g'+ctx.sharedDefs.length;type3.symbols.set(key,id);for(var i=0;i<local.defs.length;i++)ctx.sharedDefs.push(local.defs[i]);ctx.sharedDefs.push('<symbol id="'+id+'" overflow="visible">'+markup+'</symbol>');if(!local.defs.length)ctx.type3MarkupCache.set(markup,id);ctx.report.type3Glyphs++;return id;
  }
  async function imageSource(ctx,stm,page){if(ctx.imageCache.has(stm))return ctx.imageCache.get(stm);var promise=(async function(){var doc=ctx.doc,got=await doc.streamBytes(stm),w=number(doc,stm.dict.get('Width')),h=number(doc,stm.dict.get('Height')),space=nameOf(doc,stm.dict.get('ColorSpace'));if(number(doc,stm.dict.get('ImageMask'))){throw new Error('模板图片依赖当前填充色，请对照原文件验收');}if(got.filter&&isName(got.filter,'DCTDecode')&&!stm.dict.has('SMask')){if(space==='DeviceCMYK')throw new Error('CMYK JPEG 的浏览器色彩还原不稳定，请对照原文件验收');ctx.report.images++;return {url:'data:image/jpeg;base64,'+bytesToBase64(got.data),width:w,height:h};}if(got.filter&&isName(got.filter,'JPXDecode')&&!stm.dict.has('SMask')){ctx.report.images++;pageWarn(page,'jpx');ctx.warn('jpx','JPEG 2000 图片交给浏览器尝试显示，请对照原文件验收');return {url:'data:image/jp2;base64,'+bytesToBase64(got.data),width:w,height:h};}if(got.filter)throw new Error('图片过滤器 '+nameOf(doc,got.filter)+' 暂不能重建');var raw=await rawRGBA(ctx,stm,got.data),png=await rgbaPNG(raw.width,raw.height,raw.rgba);ctx.report.images++;return {url:'data:image/png;base64,'+bytesToBase64(png),width:raw.width,height:raw.height};})().catch(function(e){pageWarn(page,'image');ctx.warn('image',e.message);return null;});ctx.imageCache.set(stm,promise);return promise;}
  function xobject(ctx,name,resources){var xo=asDict(ctx.doc,resources&&resources.get('XObject'));return xo?resolved(ctx.doc,xo.get(name)):null;}
  async function renderContent(ctx,page,bytes,resources,state,depth,seen){
    if(depth>MAX_DEPTH){pageWarn(page,'recursion');ctx.warn('recursion','表单 XObject 嵌套过深');return;}
    var lex=new Lex(bytes),stack=[],saved=[],path={d:[],start:null,current:null},pendingClip=0,opCount=0;
    function resetPath(){path={d:[],start:null,current:null};}
    function applyClip(even){if(!path.d.length)return;var id='p'+page.index+'c'+page.defs.length;page.defs.push('<clipPath id="'+id+'" clipPathUnits="userSpaceOnUse"><path d="'+attr(path.d.join(' '))+'" clip-rule="'+(even?'evenodd':'nonzero')+'"/></clipPath>');state.clips.push(id);}
    function paint(fill,stroke,even,close){if(close&&path.start)path.d.push('Z');if(pendingClip){applyClip(pendingClip===2);pendingClip=0;}if(path.d.length&&(fill||stroke)){addElement(ctx,page,'<path d="'+attr(path.d.join(' '))+'"'+pathStyle(state,fill,stroke,even)+'/>',state.clips);ctx.report.vectors++;}resetPath();}
    function moveText(tx,ty){state.lineMatrix=mul(state.lineMatrix,[1,0,0,1,+tx||0,+ty||0]);state.textMatrix=state.lineMatrix.slice();}
    async function showText(str){if(!(str instanceof PStr))return;var info=await fontInfo(ctx,state.fontKey,resources);if(info&&info.mappingFallback&&!info.type3){pageWarn(page,'font-mapping');ctx.warn('font-mapping','字体 '+info.base+' 缺少可靠 ToUnicode 映射，文字复制或字形需要对照原文件验收');}if(info&&info.unavailable){pageWarn(page,'font-unavailable');ctx.warn('font-unavailable','字体 '+info.base+' 未内嵌且不是 PDF 标准字体，已使用安全替代');}var decoded=decodeText(info,str.bytes),advance=0,cursor=0,uses=[];for(var i=0;i<decoded.codes.length;i++){var item=decoded.codes[i],width=info?(info.widths.get(item.code)||standardWidth(info.base,item.code)||info.defaultWidth):1000,step=width/1000*state.fontSize+state.charSpace+(item.text===' '?state.wordSpace:0);if(info&&info.type3){var symbol=await type3Symbol(ctx,page,info,item.code,depth,seen);if(symbol)uses.push('<use href="#'+symbol+'" x="'+fmt(cursor/state.fontSize)+'"/>');}cursor+=step;advance+=step;}if(decoded.text){var tm=mul(state.ctm,state.textMatrix),rise=mul(tm,[1,0,0,1,0,state.rise]),mode=Math.max(0,Math.min(7,state.renderMode|0)),opacity=mode===3||mode===7?0:1,fill=mode===0||mode===2||mode===4||mode===6?state.fill:'none',stroke=mode===1||mode===2||mode===5||mode===6?state.stroke:'none',family=info?info.family:'Arial,sans-serif',visual;if(uses.length){var glyphBase=mul(state.ctm,mul(state.textMatrix,[state.fontSize*state.hScale,0,0,state.fontSize,0,state.rise])),glyphStyle='color:'+state.fill+';opacity:'+fmt(state.fillAlpha)+(state.blend!=='normal'?';mix-blend-mode:'+state.blend:'');visual='<g><g transform="'+matrix(glyphBase)+'" style="'+attr(glyphStyle)+'">'+uses.join('')+'</g><text xml:space="preserve" transform="'+matrix(rise)+' scale('+fmt(state.hScale)+' -1)" x="0" y="0" font-family="'+attr(family)+'" font-size="'+fmt(state.fontSize)+'" fill="transparent" stroke="none"'+(advance>0?' textLength="'+fmt(advance)+'" lengthAdjust="spacingAndGlyphs"':'')+'>'+esc(decoded.text)+'</text></g>';}else visual='<text xml:space="preserve" transform="'+matrix(rise)+' scale('+fmt(state.hScale)+' -1)" x="0" y="0" font-family="'+attr(family)+'" font-size="'+fmt(state.fontSize)+'" fill="'+attr(fill)+'" stroke="'+attr(stroke)+'" fill-opacity="'+fmt(state.fillAlpha*opacity)+'" stroke-opacity="'+fmt(state.strokeAlpha*opacity)+'"'+(advance>0?' textLength="'+fmt(advance)+'" lengthAdjust="spacingAndGlyphs"':'')+(state.blend!=='normal'?' style="mix-blend-mode:'+state.blend+'"':'')+'>'+esc(decoded.text)+'</text>';addElement(ctx,page,visual,state.clips);ctx.report.textRuns++;}state.textMatrix=mul(state.textMatrix,[1,0,0,1,advance*state.hScale,0]);}
    async function operator(op,a){var x,y,p1,p2,p3,obj,form,m,res,dict;
      switch(op){
        case 'q':saved.push(cloneGS(state));break;
        case 'Q':if(saved.length)state=Object.assign(state,saved.pop());break;
        case 'cm':if(a.length>=6)state.ctm=mul(state.ctm,a.slice(-6).map(Number));break;
        case 'w':state.lineWidth=+a.pop()||1;break;case 'J':state.lineCap=+a.pop()||0;break;case 'j':state.lineJoin=+a.pop()||0;break;case 'M':state.miter=+a.pop()||10;break;
        case 'd':state.dash=Array.isArray(a[0])?a[0].map(Number):[];state.dashPhase=+a[1]||0;break;
        case 'g':state.fillSpace='DeviceGray';state.fill=colorGray(a.pop());break;case 'G':state.strokeSpace='DeviceGray';state.stroke=colorGray(a.pop());break;
        case 'rg':state.fillSpace='DeviceRGB';state.fill=colorRGB(a.slice(-3));break;case 'RG':state.strokeSpace='DeviceRGB';state.stroke=colorRGB(a.slice(-3));break;
        case 'k':state.fillSpace='DeviceCMYK';state.fill=colorCMYK(a.slice(-4));break;case 'K':state.strokeSpace='DeviceCMYK';state.stroke=colorCMYK(a.slice(-4));break;
        case 'cs':state.fillSpace=a.length&&a[a.length-1] instanceof Name?a[a.length-1].name:'';break;
        case 'CS':state.strokeSpace=a.length&&a[a.length-1] instanceof Name?a[a.length-1].name:'';break;
        case 'sc':case 'scn':if(state.fillSpace==='DeviceGray'&&a.length>=1)state.fill=colorGray(a[0]);else if(state.fillSpace==='DeviceRGB'&&a.length>=3)state.fill=colorRGB(a);else if(state.fillSpace==='DeviceCMYK'&&a.length>=4)state.fill=colorCMYK(a);else if(state.fillSpace==='Pattern'){var fillName='';for(var ai=a.length-1;ai>=0;ai--)if(a[ai] instanceof Name){fillName=a[ai].name;break;}var fillPattern=fillName&&await patternPaint(ctx,page,fillName,resources,state,depth,seen,state.fill);if(fillPattern)state.fill='url(#'+fillPattern+')';else{pageWarn(page,'pattern');ctx.warn('pattern','PDF 填充图案 '+fillName+' 暂不能等价重建');}}else{pageWarn(page,'color-space');ctx.warn('color-space','自定义填充色彩空间需要对照原文件验收');}break;
        case 'SC':case 'SCN':if(state.strokeSpace==='DeviceGray'&&a.length>=1)state.stroke=colorGray(a[0]);else if(state.strokeSpace==='DeviceRGB'&&a.length>=3)state.stroke=colorRGB(a);else if(state.strokeSpace==='DeviceCMYK'&&a.length>=4)state.stroke=colorCMYK(a);else if(state.strokeSpace==='Pattern'){var strokeName='';for(ai=a.length-1;ai>=0;ai--)if(a[ai] instanceof Name){strokeName=a[ai].name;break;}var strokePattern=strokeName&&await patternPaint(ctx,page,strokeName,resources,state,depth,seen,state.stroke);if(strokePattern)state.stroke='url(#'+strokePattern+')';else{pageWarn(page,'pattern');ctx.warn('pattern','PDF 描边图案 '+strokeName+' 暂不能等价重建');}}else{pageWarn(page,'color-space');ctx.warn('color-space','自定义描边色彩空间需要对照原文件验收');}break;
        case 'gs':dict=asDict(ctx.doc,asDict(ctx.doc,resources&&resources.get('ExtGState'))&&asDict(ctx.doc,resources.get('ExtGState')).get(a[0]&&a[0].name));if(dict){if(dict.has('ca'))state.fillAlpha=number(ctx.doc,dict.get('ca'),1);if(dict.has('CA'))state.strokeAlpha=number(ctx.doc,dict.get('CA'),1);if(dict.has('LW'))state.lineWidth=number(ctx.doc,dict.get('LW'),1);var bm=resolved(ctx.doc,dict.get('BM'));if(Array.isArray(bm))bm=bm[0];state.blend=blend(nameOf(ctx.doc,bm));var soft=resolved(ctx.doc,dict.get('SMask'));if(soft&&!isName(soft,'None')){pageWarn(page,'soft-mask');ctx.warn('soft-mask','图形状态软蒙版需要对照原文件验收');}}break;
        case 'm':if(a.length>=2){p1=pathPoint(path,state,a[a.length-2],a[a.length-1],'M');path.start=p1;path.current=p1;}break;
        case 'l':if(a.length>=2){p1=pathPoint(path,state,a[a.length-2],a[a.length-1],'L');path.current=p1;}break;
        case 'c':if(a.length>=6){p1=point(state.ctm,+a[a.length-6],+a[a.length-5]);p2=point(state.ctm,+a[a.length-4],+a[a.length-3]);p3=point(state.ctm,+a[a.length-2],+a[a.length-1]);path.d.push('C'+fmt(p1[0])+' '+fmt(p1[1])+' '+fmt(p2[0])+' '+fmt(p2[1])+' '+fmt(p3[0])+' '+fmt(p3[1]));path.current=p3;}break;
        case 'v':if(a.length>=4){p1=path.current||[0,0];p2=point(state.ctm,+a[a.length-4],+a[a.length-3]);p3=point(state.ctm,+a[a.length-2],+a[a.length-1]);path.d.push('C'+fmt(p1[0])+' '+fmt(p1[1])+' '+fmt(p2[0])+' '+fmt(p2[1])+' '+fmt(p3[0])+' '+fmt(p3[1]));path.current=p3;}break;
        case 'y':if(a.length>=4){p1=point(state.ctm,+a[a.length-4],+a[a.length-3]);p3=point(state.ctm,+a[a.length-2],+a[a.length-1]);path.d.push('C'+fmt(p1[0])+' '+fmt(p1[1])+' '+fmt(p3[0])+' '+fmt(p3[1])+' '+fmt(p3[0])+' '+fmt(p3[1]));path.current=p3;}break;
        case 'h':path.d.push('Z');path.current=path.start;break;
        case 're':if(a.length>=4){x=+a[a.length-4];y=+a[a.length-3];var w=+a[a.length-2],h=+a[a.length-1],pa=point(state.ctm,x,y),pb=point(state.ctm,x+w,y),pc=point(state.ctm,x+w,y+h),pd=point(state.ctm,x,y+h);path.d.push('M'+fmt(pa[0])+' '+fmt(pa[1])+'L'+fmt(pb[0])+' '+fmt(pb[1])+'L'+fmt(pc[0])+' '+fmt(pc[1])+'L'+fmt(pd[0])+' '+fmt(pd[1])+'Z');path.start=pa;path.current=pa;}break;
        case 'W':pendingClip=1;break;case 'W*':pendingClip=2;break;
        case 'S':paint(false,true,false,false);break;case 's':paint(false,true,false,true);break;
        case 'f':case 'F':paint(true,false,false,false);break;case 'f*':paint(true,false,true,false);break;
        case 'B':paint(true,true,false,false);break;case 'B*':paint(true,true,true,false);break;case 'b':paint(true,true,false,true);break;case 'b*':paint(true,true,true,true);break;
        case 'n':if(pendingClip){applyClip(pendingClip===2);pendingClip=0;}resetPath();break;
        case 'Do':if(!a.length||!(a[a.length-1] instanceof Name))break;obj=xobject(ctx,a[a.length-1].name,resources);if(!(obj instanceof PStream))break;if(isName(resolved(ctx.doc,obj.dict.get('Subtype')),'Image')){var src=await imageSource(ctx,obj,page);if(src){var im='<image href="'+src.url+'" x="0" y="0" width="1" height="1" preserveAspectRatio="none" transform="'+matrix(mul(state.ctm,[1,0,0,-1,0,1]))+'"/>';addElement(ctx,page,im,state.clips);}}else if(isName(resolved(ctx.doc,obj.dict.get('Subtype')),'Form')){var refKey=obj.dict.get('Name')||obj;if(seen.indexOf(refKey)>=0){pageWarn(page,'recursion');break;}m=asArray(ctx.doc,obj.dict.get('Matrix'))||ID;res=asDict(ctx.doc,obj.dict.get('Resources'))||resources;var fstate=cloneGS(state);fstate.ctm=mul(state.ctm,m.map(Number));var bbox=asArray(ctx.doc,obj.dict.get('BBox'));if(bbox&&bbox.length>=4){var ba=point(fstate.ctm,+bbox[0],+bbox[1]),bb=point(fstate.ctm,+bbox[2],+bbox[1]),bc=point(fstate.ctm,+bbox[2],+bbox[3]),bd=point(fstate.ctm,+bbox[0],+bbox[3]),clipId='p'+page.index+'f'+page.defs.length;page.defs.push('<clipPath id="'+clipId+'" clipPathUnits="userSpaceOnUse"><path d="M'+fmt(ba[0])+' '+fmt(ba[1])+'L'+fmt(bb[0])+' '+fmt(bb[1])+'L'+fmt(bc[0])+' '+fmt(bc[1])+'L'+fmt(bd[0])+' '+fmt(bd[1])+'Z"/></clipPath>');fstate.clips.push(clipId);}var group=asDict(ctx.doc,obj.dict.get('Group'));if(group&&isName(resolved(ctx.doc,group.get('S')),'Transparency')){pageWarn(page,'transparency-group');ctx.warn('transparency-group','透明度表单组的隔离与挖空语义需要对照原文件验收');}var body=await ctx.doc.streamBytes(obj);if(body.filter){pageWarn(page,'form');ctx.warn('form-filter','表单内容流过滤器无法解码');}else await renderContent(ctx,page,body.data,res,fstate,depth+1,seen.concat([refKey]));}break;
        case 'BI':lex.skipInlineImage();pageWarn(page,'inline-image');ctx.warn('inline-image','检测到暂不能重建的内联图片，请对照原文件验收');break;
        case 'BT':state.inText=true;state.textMatrix=ID.slice();state.lineMatrix=ID.slice();break;case 'ET':state.inText=false;break;
        case 'Tf':if(a.length>=2){state.fontKey=a[a.length-2] instanceof Name?a[a.length-2].name:'';state.fontSize=+a[a.length-1]||12;}break;
        case 'Tm':if(a.length>=6){state.textMatrix=a.slice(-6).map(Number);state.lineMatrix=state.textMatrix.slice();}break;
        case 'Td':if(a.length>=2)moveText(a[a.length-2],a[a.length-1]);break;
        case 'TD':if(a.length>=2){state.leading=-(+a[a.length-1]||0);moveText(a[a.length-2],a[a.length-1]);}break;
        case 'T*':moveText(0,-state.leading);break;
        case 'Tj':await showText(a[a.length-1]);break;
        case 'TJ':var list=a[a.length-1];if(Array.isArray(list))for(var z=0;z<list.length;z++){if(list[z] instanceof PStr)await showText(list[z]);else if(typeof list[z]==='number')state.textMatrix=mul(state.textMatrix,[1,0,0,1,-list[z]/1000*state.fontSize*state.hScale,0]);}break;
        case "'":moveText(0,-state.leading);await showText(a[a.length-1]);break;
        case '"':if(a.length>=3){state.wordSpace=+a[a.length-3]||0;state.charSpace=+a[a.length-2]||0;moveText(0,-state.leading);await showText(a[a.length-1]);}break;
        case 'Tc':state.charSpace=+a.pop()||0;break;case 'Tw':state.wordSpace=+a.pop()||0;break;case 'Tz':state.hScale=(+a.pop()||100)/100;break;case 'TL':state.leading=+a.pop()||0;break;case 'Tr':state.renderMode=+a.pop()||0;if(state.renderMode>=4){pageWarn(page,'text-clip');ctx.warn('text-clip','文字轮廓裁剪需要对照原文件验收');}break;case 'Ts':state.rise=+a.pop()||0;break;
        case 'sh':pageWarn(page,'shading');ctx.warn('shading','渐变/网格着色属于 PDF 专有绘制，请对照原文件验收');break;
        case 'BDC':if(a.length&&a[0] instanceof Name&&a[0].name==='OC'){pageWarn(page,'optional-content');ctx.warn('optional-content','PDF 可选图层的显隐状态需要对照原文件验收');}break;
        case 'BMC':case 'EMC':case 'MP':case 'DP':case 'BX':case 'EX':case 'ri':case 'i':case 'd0':case 'd1':break;
        default:if(op&&op.length<8){pageWarn(page,'operator');ctx.warn('operator','未识别内容操作符 '+op);}
      }
    }
    while(lex.p<bytes.length){abort(ctx.options.signal);var token=lex.next(0);if(token&&token.op){await operator(token.op,stack);stack=[];}else if(token!==null)stack.push(token);if((++opCount&1023)===0)await frame();}
  }

  async function contentBytes(doc,page){var c=resolved(doc,page.dict.get('Contents')),list=Array.isArray(c)?c:[c],chunks=[];for(var i=0;i<list.length;i++){var stm=resolved(doc,list[i]);if(!(stm instanceof PStream))continue;var got=await doc.streamBytes(stm);if(got.filter)throw new Error('页面内容流过滤器 '+nameOf(doc,got.filter)+' 暂不能解码');chunks.push(got.data);chunks.push(new Uint8Array([10]));}return C.concat(chunks);}
  function annotationSvg(ctx,page,pm){var doc=ctx.doc,list=asArray(doc,page.source.dict.get('Annots'))||[],out='';for(var i=0;i<list.length;i++){var a=asDict(doc,list[i]);if(!a)continue;var subtype=nameOf(doc,a.get('Subtype'));if(subtype!=='Link'){pageWarn(page,subtype==='Widget'?'forms':'annotations');ctx.warn(subtype==='Widget'?'forms':'annotations',subtype==='Widget'?'交互表单不会写入纯净页面 HTML，请对照原文件验收':'可视注释 '+subtype+' 不会写入纯净页面 HTML');continue;}var rect=asArray(doc,a.get('Rect'));if(!rect||rect.length<4)continue;var action=asDict(doc,a.get('A')),uri=action&&resolved(doc,action.get('URI')),url=uri instanceof PStr?safeUrl(latin(uri.bytes)):'';if(!url){pageWarn(page,'internal-link');ctx.warn('internal-link','页内跳转或书签链接需要对照原文件验收');continue;}var x=Math.min(+rect[0],+rect[2]),y=Math.min(+rect[1],+rect[3]),w=Math.abs(+rect[2]-+rect[0]),h=Math.abs(+rect[3]-+rect[1]);out+='<a href="'+attr(url)+'" target="_blank" rel="noopener noreferrer"><rect x="'+fmt(x)+'" y="'+fmt(y)+'" width="'+fmt(w)+'" height="'+fmt(h)+'" fill="transparent" pointer-events="all"><title>'+esc(url)+'</title></rect></a>';ctx.report.links++;}return out?'<g transform="'+matrix(pm)+'">'+out+'</g>':'';}

  /* ---------- 单文件 HTML ---------- */
  function makeHTML(ctx,title){
    var en=ctx.options.locale==='en',lang=en?'en':'zh-CN',pageLabel=en?'PDF page ':'PDF 第 ',shared=ctx.sharedDefs&&ctx.sharedDefs.length?'<svg class="pdf-shared-defs" aria-hidden="true"><defs>'+ctx.sharedDefs.join('')+'</defs></svg>':'',pageHTML=ctx.pages.map(function(page,index){return '<section class="pdf-page" style="--page-width:'+fmt(page.width)+';--page-height:'+fmt(page.height)+'" aria-label="'+pageLabel+(index+1)+'">'+page.svg+'</section>';}).join(''),metadata={schema:'https://imging.cn/schemas/pdf-html/1',title:title,pages:ctx.pages.map(function(page){return {width:page.width,height:page.height,quality:page.quality,flags:page.flags};}),report:ctx.report,warnings:ctx.warnings},json=JSON.stringify(metadata).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');
    return '<!doctype html><html lang="'+lang+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="ImgIng PDF to HTML"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; img-src data:; style-src \'unsafe-inline\'; font-src data:"><title>'+esc(title)+'</title><style>'+ctx.fontFaces.join('')+
      ':root{color-scheme:light dark;--reader-bg:#e7eceb;--page-shadow:0 18px 52px rgba(24,35,33,.18)}@media(prefers-color-scheme:dark){:root{--reader-bg:#171b1a;--page-shadow:0 20px 58px rgba(0,0,0,.5)}}*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--reader-bg)}.pdf-shared-defs{position:absolute;width:0;height:0;overflow:hidden}main{display:grid;justify-items:center;gap:20px;padding:24px 16px}.pdf-page{position:relative;width:min(calc(var(--page-width) * 1px),calc(100vw - 32px));aspect-ratio:var(--page-width)/var(--page-height);overflow:hidden;background:#fff;box-shadow:var(--page-shadow);content-visibility:auto;contain:layout paint style}.pdf-page svg{display:block;width:100%;height:100%}@media(max-width:640px){main{gap:12px;padding:12px 6px}.pdf-page{width:min(calc(var(--page-width) * 1px),calc(100vw - 12px))}}@media print{:root{--reader-bg:#fff}main{gap:0;padding:0}.pdf-page{width:100%;box-shadow:none;break-after:page;page-break-after:always;content-visibility:visible;contain:none}.pdf-page:last-child{break-after:auto;page-break-after:auto}}</style></head><body>'+shared+'<main aria-label="'+esc(en?'Converted PDF pages':'转换后的 PDF 页面')+'">'+pageHTML+'</main><script type="application/json" id="imging-pdf-metadata">'+json+'</script></body></html>';
  }

  async function convert(bytes,options){
    options=options||{};if(!(bytes instanceof Uint8Array))bytes=new Uint8Array(bytes);abort(options.signal);progress(options,'parse',2,'正在解析 PDF 结构');var doc=await C.load(bytes),allSources=doc.pages();if(!allSources.length)throw new Error('PDF 没有可转换的页面');if(allSources.length>MAX_PAGES)throw new Error('PDF 页数超过 '+MAX_PAGES+' 页安全上限');var sourcePages=allSources.length,pageLimit=Math.floor(+options.pageLimit||0),sources=pageLimit>0?allSources.slice(0,Math.min(sourcePages,pageLimit)):allSources,title=String(options.title||'PDF-固定版式页面').replace(/[\u0000-\u001f]/g,' ').trim()||'PDF-固定版式页面';
    var ctx={doc:doc,options:options,pages:[],sharedDefs:[],type3MarkupCache:new Map(),fontFaces:[],fontCache:new Map(),imageCache:new Map(),patternCache:new Map(),warnings:[],warningKeys:new Set(),report:{pages:sources.length,sourcePages:sourcePages,elements:0,textRuns:0,vectors:0,images:0,links:0,fontsEmbedded:0,fontsRestricted:0,type3Glyphs:0,patterns:0,pagesHigh:0,pagesFallback:0},warn:function(code,text){var key=code+'|'+text;if(!this.warningKeys.has(key)){this.warningKeys.add(key);this.warnings.push({code:code,message:text});}}};
    for(var i=0;i<sources.length;i++){abort(options.signal);var source=sources[i],box=asArray(doc,source.inherited.CropBox)||asArray(doc,source.inherited.MediaBox)||[0,0,612,792];box=box.map(function(v){return number(doc,v);});if(box.length<4||box[2]<=box[0]||box[3]<=box[1])box=[0,0,612,792];var rotate=number(doc,source.inherited.Rotate),user=number(doc,source.dict.get('UserUnit'),1)||1,pm=pageMatrix(box,rotate,user),page={index:i+1,source:source,outputMatrix:pm.m,width:Math.round(pm.width*1000)/1000,height:Math.round(pm.height*1000)/1000,elements:[],defs:[],flags:[],quality:'high'};ctx.pages.push(page);progress(options,'pages',5+(i/sources.length)*84,'正在重建第 '+(i+1)+' / '+sources.length+' 页');try{var content=await contentBytes(doc,source),resources=asDict(doc,source.inherited.Resources)||new Dict();await renderContent(ctx,page,content,resources,gs(),0,[]);}catch(e){pageWarn(page,'content');ctx.warn('content','第 '+(i+1)+' 页：'+e.message);}var body=(page.defs.length?'<defs>'+page.defs.join('')+'</defs>':'')+'<g transform="'+matrix(pm.m)+'">'+page.elements.join('')+'</g>'+annotationSvg(ctx,page,pm.m);page.quality=page.flags.length?'fallback':'high';if(page.quality==='high')ctx.report.pagesHigh++;else ctx.report.pagesFallback++;page.svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+fmt(page.width)+' '+fmt(page.height)+'" role="img" aria-label="PDF page '+(i+1)+'">'+body+'</svg>';delete page.elements;delete page.defs;delete page.source;if(i===0&&typeof options.onFirstPage==='function'){var previewReport=Object.assign({},ctx.report,{pages:1,sourcePages:sourcePages,originalBytes:bytes.length,selfContained:true,originalFallback:false,viewerControls:false}),previewCtx={options:options,pages:[page],sharedDefs:ctx.sharedDefs.slice(),fontFaces:ctx.fontFaces.slice(),report:previewReport,warnings:ctx.warnings.slice()};try{options.onFirstPage({html:makeHTML(previewCtx,title),sourcePages:sourcePages});}catch(_previewError){}}if((i&3)===3)await frame();}
    progress(options,'package',92,'正在封装字体、图片与纯净页面 HTML');ctx.report.originalBytes=bytes.length;ctx.report.selfContained=true;ctx.report.originalFallback=false;ctx.report.viewerControls=false;var html=makeHTML(ctx,title),external=/(?:<script\b[^>]*\bsrc\s*=|<link\b[^>]*\bhref\s*=|@import\s+)/i.test(html);if(external)throw new Error('单文件校验失败：发现外部资源引用');ctx.report.outputBytes=new Blob([html]).size;progress(options,'done',100,'纯净页面 HTML 已生成');return {html:html,pages:ctx.pages.length,report:ctx.report,warnings:ctx.warnings,title:title,mime:'text/html'};
  }

  W.TYPDFToHTML={convert:convert,version:'1.1.0'};
})();
